name: Build CalcUnix
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install GCC
        run: sudo apt update && sudo apt install -y build-essential
      - name: Build with Make
        run: make
      - name: Run Test
        run: ./calcunix
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: CalcUnix-Build
          path: |
            calcunix
            Calculate.so
